# 双GPU优化配置 - 解决内存和任务分片问题
exp_name: pi0_dual_gpu_optimized

# --- 路径配置 ---
policy_path: "/zhaohan/ZJH/openpi_pytorch/checkpoints/pi0_libero_pytorch"
output_dir: "./pi0/ript/output/dual_gpu_optimized"  
norm_stats_path: "/zhaohan/ZJH/openpi_pytorch/lerobot_dataset/norm_stats.json"

# --- 分布式配置 ---
distributed:
  enabled: true
  backend: 'nccl'
  timeout_seconds: 3600
  find_unused_parameters: false
  bucket_cap_mb: 15                    # 减少通信开销

# --- 数据并行配置 ---
data_parallel:
  sync_every_n_steps: 2
  enable_gradient_checkpointing: true  # 启用梯度检查点节省内存
  async_data_loading: false

# --- 任务分片配置 ---
task_distribution:
  enable_task_sharding: false          # 关闭任务分片，两个GPU处理相同任务
  balance_tasks_across_gpus: false
  min_tasks_per_gpu: 1

# --- 任务和环境配置 ---
task:
  benchmark_name: "libero_spatial" 
  task_name: 9
  task_names_to_use: null
  num_parallel_envs: 2                 # 减少并行环境数
  rollouts_per_env: 2                  # 减少每环境轨迹数
  max_episode_length: 50               # 大幅缩短episode长度

# --- 算法配置（内存优化） ---
algo:
  rloo_batch_size: 2                   # 减小batch大小
  num_epochs: 1                        # 减少epochs
  data_batch_size: 2                   # 减小总batch数
  gradient_accumulation_steps: 1       # 简化梯度累积
  lr: 1e-5
  grad_norm_clip: 1.0
  
  enable_dynamic_sampling: true
  enable_rollout_stats_tracking: false  # 关闭统计跟踪节省内存
  rollout_skip_threshold: 2
  rollout_stats_path: "./pi0/ript/output/dual_gpu_optimized/rollout_stats.json"
  use_val_init: false

# --- 训练配置 ---  
training:
  num_train_steps: 2                   # 只运行2步测试
  seed: 42
  save_freq: 5
  save_best: false
  use_mixed_precision: true            # 启用混合精度节省内存
  
  optimizer:
    type: "AdamW"
    weight_decay: 0.005                # 减少权重衰减

# --- 日志配置 ---
logging:
  use_wandb: false
  log_freq: 1
  log_gradients: false
  log_dir: "./pi0/ript/output/dual_gpu_optimized/logs"

# --- 增强采样配置 ---
enhanced_sampling:
  enable_smart_filtering: false        # 关闭智能过滤
  max_sampling_attempts: 2             # 减少尝试次数
  debug_sampling: false                # 关闭调试采样
  save_videos: false                   # 不保存视频节省内存
  video_dir: "rollout_videos_dual"

# --- 性能优化配置 ---
performance:
  enable_torch_compile: false
  max_memory_per_gpu_gb: 14            # 降低内存限制，为两个进程预留空间
  prefetch_factor: 1
  num_workers: 1                       # 减少worker数量
  pin_memory: false                    # 关闭内存锁定
  
# --- 容错和恢复配置 ---
fault_tolerance:
  enable_checkpointing: false
  auto_resume: false

# --- 调试配置 ---
debug:
  profile_performance: false           # 关闭性能分析
  log_memory_usage: true              # 保持内存监控
  save_intermediate_results: false
  distributed_debug: false